name: test

on:
  push:
    branches:
      - "**"
  pull_request:

permissions:
  contents: read

jobs:
  node:
    name: node ${{ matrix.node-version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 22.13.0
          - 22.x
          - 23.x
          - 24.x
          - 25.x
          - 26.x

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}

      - name: Enforce conventional commits
        uses: webiny/action-conventional-commits@7f91b1595ca1951cdb671ddc9f07a49081ec5b69

      - run: npm ci
      - run: npm run lint
      - run: npm run typecheck
      - run: npm run build
      - run: npm test

  react:
    name: react ${{ matrix.react }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - react: 16
            testFileFilter: src/__tests__/index.test.tsx
          - react: 17
            testFileFilter: src/__tests__/index.test.tsx
          - react: 18
            testFileFilter: ""
          - react: 19
            testFileFilter: ""

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 26.x

      - name: Downgrade react to v${{ matrix.react }}
        run: |
          npm pkg set devDependencies.react=${{ matrix.react }} devDependencies.react-dom=${{ matrix.react }}
          npm i --force

      - run: npm test -- ${{ matrix.testFileFilter }}
